### PR TITLE
Modify rule S2589,S3516,S3626: Remove them from CFamily (CPP-5165)

### PR DESCRIPTION
**Pull request by pdschbrt**
## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

### CODE REVIEW

**Comment by pdschbrt** [comment]
I wonder who's responsible for updating `frontend/public/covered_rules.json`. Is it automatically updated?

**Review by frederic-tingaud-sonarsource — CHANGES_REQUESTED** [review]
My understanding from the meeting and from the JIRA ticket was that we want to remove those rules altogether, not just remove them from SonarWay.
That would mean changing the metadata.json to have `"status": "closed"`.

**Comment by pdschbrt** [comment]
> My understanding from the meeting and from the JIRA ticket was that we want to remove those rules altogether, not just remove them from SonarWay. That would mean changing the metadata.json to have `"status": "closed"`.

Yes, indeed. I'll address this and change the status after lunch.

**Comment by pdschbrt** [comment]
@frederic-tingaud-sonarsource I've "closed" these rules now. Is there anything else to do within the RSPEC repo in order to remove them?

**Review by frederic-tingaud-sonarsource — APPROVED** [review]

**Comment by frederic-tingaud-sonarsource** [comment]
It should be good on RSPEC side.

**Pull request merged**
