### PR TITLE
Modify rule S5146: Add fix for Blazor (APPSEC-1905)

### PR DESCRIPTION
**Pull request by daniel-teuchert-sonarsource**
## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

### CODE REVIEW

**Review by hendrik-buchwald-sonarsource — APPROVED** [review]
LGTM

**Comment by thomas-serre-sonarsource** [comment]
@daniel-teuchert-sonarsource I'm not able to get the `validate_links` test green in the CI. Could you help me get this PR green?

**Comment by daniel-teuchert-sonarsource** [comment]
> @daniel-teuchert-sonarsource I'm not able to get the `validate_links` test green in the CI. Could you help me get this PR green?

@thomas-serre-sonarsource I looked at the details of the failing test, and it seems to be coming from a URL unrelated to the changes in this PR (https://www.kernel.org/doc/Documentation/prctl/no_new_privs.txt).
This failing test was mentioned in https://sonarsource.slack.com/archives/CFSLVKNBB/p1725019940627589 and I think a ticket was already created for it.

Do you need this test to pass? I think you can merge anyway.

**Comment by thomas-serre-sonarsource** [comment]
I will merge it then :) thanks for the quick reply!

**Pull request merged**
