### PR TITLE
RULEAPI-660: Add an exception to the new-rule workflow

### PR DESCRIPTION
**Pull request by arseniy-sonar**

### CODE REVIEW

**Review by pavel-mikula-sonarsource — APPROVED** [review]
LGTM

**Comment by pavel-mikula-sonarsource** [comment]
CI doesn't like the link with restricted access 403 :)

**Comment by pavel-mikula-sonarsource** [comment]
We can use just `ticket RULEAPI-600` without an URL

**Comment by arseniy-sonar** [comment]
> CI doesn't like the link with restricted access 403 :)

The links are not blocking the merge, we plan to run them nightly and display on the wellboard in the future.

**Comment by pavel-mikula-sonarsource** [comment]
It failed on 403 access denied to the private JIRA project. Let's just remove the URL, we can live without it for simplicity.

**Comment by arseniy-sonar** [comment]
> It failed on 403 access denied to the private JIRA project. Let's just remove the URL, we can live without it for simplicity.

I believe it failed on this url: https://cirrus-ci.com/task/6067931835531264?logs=tests#L2179
Normally, the `validate_links` scans only the rule specifications and ignores the readme.adoc

**Comment by pavel-mikula-sonarsource** [comment]
Indeed, RULEAPI is a public project 🤦‍♂️

**Pull request merged**
