### PR TITLE
RULEAPI-665: Remove security standards from the irrelevant language-specific rules

### PR DESCRIPTION
**Pull request by arseniy-sonar**

### CODE REVIEW

**Comment by arseniy-sonar** [comment]
I used the following script to fix the metadata:
```
`use strict`;

const fs = require('fs');
const path = require('path');

const writeJson = function(data, path) {
  let jsonContent = JSON.stringify(data, null, 2);
  jsonContent = jsonContent.replace(/\//g, '\\/');
  jsonContent = jsonContent.replace(/( +)"(.+)": \[\]/g, '$1"$2": [\n$1  \n$1]');
  fs.writeFileSync(path, jsonContent + '\n', 'utf8');
}

const readJson = function(path) {
  let rawdata = fs.readFileSync(path);
  return JSON.parse(rawdata);
}

const addCert = function(certSpec, path) {
  let original = readJson(path);
  if ('securityStandards' in original) {
    if (!('CERT' in original['securityStandards'])) {
      original['securityStandards']['CERT'] = certSpec;
      writeJson(original, path);
    }
  } else {
    original['securityStandards'] = {'CERT': certSpec};
    writeJson(original, path);
  }
}

const remCert = function(original, path) {
  var fixed = original;
  delete fixed['securityStandards']['CERT'];
  if (!Object.keys(fixed['securityStandards']).length) {
    delete fixed['securityStandards'];
  }
  writeJson(fixed, path);
};

const ruleDirs = fs.readdirSync('.');
ruleDirs.forEach(function(dir) {
  if (fs.lstatSync(dir).isDirectory()) {
    meta = readJson(dir + '/metadata.json');
    if ('securityStandards' in meta) {
      if ('CERT' in meta['securityStandards']) {
        let certSpec = meta['securityStandards']['CERT'];
        let hasC = false;
        let hasJava = false;
        let otherLangs = [];
        ruleLangs = fs.readdirSync(dir);
        ruleLangs.forEach(function(lang) {
          if (fs.lstatSync(dir + '/' + lang).isDirectory()) {
            if (lang == 'cfamily') {
              hasC = true;
            } else if (lang == 'java') {
              hasJava = true;
            } else {
              otherLangs.push(lang);
            }
          }
        });
        if (otherLangs.length) {
          if (hasC) {
            addCert(certSpec, dir + '/cfamily/metadata.json');
          }
          if (hasJava) {
            addCert(certSpec, dir + '/java/metadata.json');
          }
          remCert(meta, dir + '/metadata.json');
        }
      }
    }
  }
});
```
Nothing is done for the rule descriptions so far.

**Comment by arseniy-sonar** [comment]
Used the following script to fix the "See" sections: https://github.com/SonarSource/languages-experimental-tooling/blob/master/personal/arseniy-zaostrovnykh/rspec/fix-cert-misra-in-see.py
Please, do not merge this PR before #346 (the last export-related PR)

**Comment by arseniy-sonar** [comment]
@vilchik-elena , with this PR, I would like to wait for #346 first. I will rerun the scripts mentioned above to regenerate the changes on top of the newly exported data.

**Review by vilchik-elena — DISMISSED** [review]

**Comment by arseniy-sonar** [comment]
Merged accidentally, rewerting in #361

**Comment by vilchik-elena** [comment]
* No tag, while standard is in top level meta: S1181, S2192, S2193, S2215, S2637, S901, S923, S979
* No standard, while with tag: java S4347, cfam S4963, java S5659, cfam and java S5693, cfam S5750, cfam and java S5757
* No tag, while with standard: java S5542, java 5547
* xml language with standard S5594
* "secrets" language (e.g. S6290), no tag

**Pull request merged**
