### PR TITLE
RULEAPI-653: Add a new language identifier for secrets detection rules

### PR DESCRIPTION
**Pull request by pierre-loup-tristant-sonarsource**
https://github.com/SonarSource/sonar-rule-api/pull/162

### CODE REVIEW

**Comment by arseniy-sonar** [comment]
@pierre-loup-tristant-sonarsource , you probably want to add "secrets" to `languageToJiraProject` map in frontend/src/RulePage.tsx, and `languageToSonarpedia` map in frontend/src/utils/useRuleCoverage.ts

**Comment by pierre-loup-tristant-sonarsource** [comment]
@arseniy-sonar I added "secrets" to `languageToSonarpedia`. Since there is not realy a Jira project for this analyzer I can add it to `languageToJiraProject`

**Comment by pierre-loup-tristant-sonarsource** [comment]
The force-push action credited to @paul-gerste-sonarsource was done by me. This is most probably a bug on GitHub's side.
It has been reported to internal security.

**Comment by pierre-loup-tristant-sonarsource** [comment]
@arseniy-sonar in the end I think it makes sens to have a Jira project. I just asked helpdesk to create one. Please don't merge the PR yes, I will add the Jira project name to `languageToJiraProject` once it's created.

**Review by arseniy-sonar — APPROVED** [review]

**Pull request merged**
