### PR TITLE
Remove rule S1477

### PR DESCRIPTION
**Pull request by csaba-sagi-sonarsource**
Deprecated, soon to be removed common rule.

### CODE REVIEW

**Review by arseniy-sonar — CHANGES_REQUESTED** [review]
The checks are failing because S1477 is left with no language specialization.
Since the rule specification contains no useful information, I propose to remove the rule entirely.

**Comment by csaba-sagi-sonarsource** [comment]
> The checks are failing because S1477 is left with no language specialization. Since the rule specification contains no useful information, I propose to remove the rule entirely.

I guess it will do no harm if we remove it, right?

**Comment by arseniy-sonar** [comment]
> I guess it will do no harm if we remove it, right?

Yep. It is always tough to remove things, but in this case, I see no value in the rule specification itself.

**Review by arseniy-sonar — APPROVED** [review]
Don't forget to update the PR title and the merge commit message

**Comment by vilchik-elena** [comment]
Should we remove all common rules from RSPEC then? what's the point of removing just one?

**Comment by csaba-sagi-sonarsource** [comment]
> Should we remove all common rules from RSPEC then? what's the point of removing just one?
Are all of those common rules deprecated and are they going to be removed? If yes, we can remove all of them.

**Comment by vilchik-elena** [comment]
@csaba-sagi-sonarsource yep, all are deprecated and all will be removed.

**Comment by csaba-sagi-sonarsource** [comment]
> @csaba-sagi-sonarsource yep, all are deprecated and all will be removed.

Do you have somewhere the list of those rules? I can create separate PRs to remove them. I would go rule by rule.

**Comment by vilchik-elena** [comment]
@csaba-sagi-sonarsource I don't think we have rule keys somewhere, but you can find the rules by title. Just take any language on Peach and open Common rule repository: https://peach.sonarsource.com/coding_rules?repositories=common-abap&selected=common-abap%3AInsufficientBranchCoverage

**Comment by csaba-sagi-sonarsource** [comment]
I will merge this PR. There are 5 other PRs to remove the 5 other deprecated common rules:

- https://github.com/SonarSource/rspec/pull/1055
- https://github.com/SonarSource/rspec/pull/1056
- https://github.com/SonarSource/rspec/pull/1057
- https://github.com/SonarSource/rspec/pull/1058
- https://github.com/SonarSource/rspec/pull/1059

**Pull request merged**
