### PR TITLE
Modify rules: Add STIG AS&D 2023-06-08 mappings

### PR DESCRIPTION
**Pull request by jamie-anderson-sonarsource**
Add mappings to US DoD Security Technical Implementation Guidelines for [Application Security and Development (2023-06-08)](https://stigviewer.com/stig/application_security_and_development/2023-06-08/).

See: [APPSEC-1711](https://sonarsource.atlassian.net/browse/APPSEC-1711)

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

[APPSEC-1711]: https://sonarsource.atlassian.net/browse/APPSEC-1711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by loris-s-sonarsource** [comment]
Looks like the `validate_link` failure is unrelated to this PR, I'll skip it

**Comment by loris-s-sonarsource** [comment]
Here are the results of my review, it looks like there was only missing rules, that I added in my commit:

<google-sheets-html-origin>
Sonar Rules | Finding ID |  
-- | -- | --
Secrets rules | V-222642 | We should add this to all secrets
S6474 | V-222618 | Misses S6474
S6423 - Azure Functions should log all failureshttps://sonarsource.github.io/rspec/#/rspec/S6776 - Stack-traces should not be disclosed | V-222610 | Misses S6423 and S6776
S6376 | V-222593 | Misses S6376
S6319, S6330, S6327, S6308, S6303 | V-222588 | There's only S6303 and S6308 here
S6270, S6281, S6329, S6333, S6404 | V-222620 | Misses S6329, S6333, S6404
S3949, S5782, S3519, S6069, S5273, S6179, S5801, S1913, S1079, S5814, S1081, S6365, S6183, S3518, S5815, S5816, S5283, S5824, S5813, S2184 | V-222612 | Missing one rule but that seems ok - nothing to do here
S2631, S6639 | V-222594 | Misses S6639
S2631, S6376, S6390, S6639, S6785plus any other DoS rules | V-222667 | Only S2631 is present, there should also be the others: S6376, S6390, S6639, S6785
S2612, S6469 | V-222430 | Missing S6469
All XML rules | V-222608 | Missing S6377, S6376, S6399, S6373
All Injection rules | V-222609 | Missing S5144, S5883, S5334, S6384, S6399 , S6398, S6390 ,  S6350

**Review by jamie-anderson-sonarsource — COMMENTED** [review]
@loris-s-sonarsource your additions look good. I found a couple of additional rules that we missed and have added yet another commit that addresses them. I've also added full stops to the end of the links, as the text is a proper sentence.

**Comment by loris-s-sonarsource** [comment]
@jamie-anderson-sonarsource Good catch, looks like my list of taint vuln is not up-to-date

**Review by loris-s-sonarsource — APPROVED** [review]
LGTM

**Pull request merged**
