### PR TITLE
SONARPY-2005: Modify rule S1721: Update rule for in (...)

### PR DESCRIPTION
**Pull request by Seppli11**
## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

### CODE REVIEW

**Comment by Seppli11** [comment]
I'm not sure if it would be wise to add another example for the `for ... in (...)` example, or maybe the description could be more clearer

**Comment by joke1196** [comment]
I think it is fine like this. The change you made is clear.

**Comment by joke1196** [comment]
Before merging could you modify the PR name to be `Modify rule S... : ...` as it seems to be the standard. Thanks!

**Review by joke1196 — APPROVED** [review]
LGTM. Thanks for taking care of this.

**Pull request merged**
