### PR TITLE
RULEAPI-666: Migrate the "List of parameters", "Highlighting" and "Message" fields from jira RSPEC

### PR DESCRIPTION
**Pull request by arseniy-sonar**
The patch for exporting these sections is here:
https://github.com/SonarSource/sonar-rule-api/compare/8394a487...az/RULEAPI-666-meta-sections
In particular, I checked that no damage has been done with this script, that undoes the export of the meta sections:
https://github.com/SonarSource/sonar-rule-api/blob/az/RULEAPI-666-meta-sections/validate-meta-section-export.sh

### CODE REVIEW

**Comment by arseniy-sonar** [comment]
The second transformation is done with
```
find . -name '*.adoc' | xargs sed -i -f ../merge-hidden.sed
```
where `merge-hidden.sed` is:
```
: more
$!N
s/\n/&/2;
t enough
$!b more
: enough
s/^endif::env-github,rspecator-view\[\]\n\nifdef::env-github,rspecator-view\[\]$/\n/
P;D
```

**Comment by andrei-epure-sonarsource** [comment]
I'll start reviewing the changes on rule-api. 
@arseniy-sonar - is there any reason why those rule-api changes are not in a PR?

**Comment by arseniy-sonar** [comment]
@andrei-epure-sonarsource, the rule-api changes are not relevant to the current rule-api version.

They affect three components:
- the export (jira->github), that was never part of the rule-api as it is necessary only for the transition
- the jira fetcher: it is no longer relevant in the new rule-api, since it only relies on github now
- the Rule class: it is not relevant to the new rule-api, since the added fields are translated into the rule description and appears just as a part of the rule description text when it is exported.

**Comment by andrei-epure-sonarsource** [comment]
Intermediate notes. I still want to evaluate "highlights" and "message" and finish the evaluation of "parameters".

The below notes are for opening tickets for future development and are not actionable on this current PR. It's a limitation of the data in JIRA.

_______________________________________________________________________________________________

I did some validation by deploying the changes locally and checking some of the rules with parameters (powershell command `Get-ChildItem -recurse "rule.adoc" | Select-String  -pattern " key =" -Context 1,4`). Overall, there isn't a standardized way of viewing parameters.

For example:

- S3008 - https://jira.sonarsource.com/browse/RSPEC-3008 . `Description` is not on its own bullet point. `Default Value` is on a separate line.
- compare this to S5998 - https://jira.sonarsource.com/browse/RSPEC-5998 - `key`, `default` and `description` have bullet points in JIRA.

The style differs also in terms of
- casing -`Type` (S100 Java) vs `type` (S100 CFamily)
- terms - `default` (S101 Python) vs `Default value` (S101 Swift)
- how bullet points are used 
  - using simple bullet points for one param - "key", "default", "description" one under another (S101 vbnet)
  - only one bullet points for one param - "key" is a bullet point, the others come after with simple `\n` or double `\n\n` which makes it look bad because "Description" is on the same line with "key" and "default" is on a separate line (S103 cfamily)
  - nested bullet points where key is the parent node and "description" and "default" are nested
    - with multiple params (S1316 cobol)
    - with single param (S2342 vbnet)

**Comment by andrei-epure-sonarsource** [comment]
Another observation: IMO "comments and links" is usually noise, many times out of date and don't help.

I would move the parameters, message and highlight section _above_ comments and links, because it's more important. And I would even make "comments and links" hidden by default, with a button to expand.

**Action Item for this PR**: show the parameters, highlighting and message before comments and links.

**Comment by andrei-epure-sonarsource** [comment]
Found bug: for S110 the parent metadata `S110\parameters.adoc` is shown in the C# rule which has its own metadata in `S110\csharp\rule.adoc`. 

Expected: if the rule has specified message/highlithing/params, only the rule-specific ones should be shown.
Actual: both the parent metadata and the rule-specific metadata is shown on the page.

See below.

image

**Comment by andrei-epure-sonarsource** [comment]
Bug: the "message" is shown inconsistently before or after the "comments and links" section.

Example where message is shown **after** "comments and links": http://localhost:3000/rspec#/rspec/S109/java
Example where message is shown **before** "comments and links": http://localhost:3000/rspec#/rspec/S1105/java

**Comment by andrei-epure-sonarsource** [comment]
First observation about "Messaging Specification" - I would rename it "Implementation specification" because parameters don't really have anything to do with "messaging" - they are just customizing the rule.

image

 I guess "message" and "highlighting" could be together under "Messaging Specification"... But I'd rather keep all 3 metadata under a common "Implementation specification"... WDYT @arseniy-sonar ?

_______________________________________________________________________________________________

Messages are inconsistent in style:

- most are a simple phrase
- however some contain bullet points which do not differentiate the message from the message condition - see http://localhost:3000/rspec#/rspec/S1045/python and below

image

**Comment by andrei-epure-sonarsource** [comment]
Highlighting review - `Get-ChildItem -recurse "*.adoc" | Select-String -pattern "Highlighting" -Context 2,10`

Inconsistency when specifying an associated message for secondary locations:
- `* Secondary` and `Message` in the same bullet point e.g. http://localhost:3000/rspec#/rspec/S1045/python
- `* Secondary` and `** message` as nested bullet point e.g. http://localhost:3000/rspec#/rspec/S110
- * Secondary` with multiple messages as nested bullet points
  - "message1" and "message2" e.g. http://localhost:3000/rspec#/rspec/S135
  - not numbered messages: http://localhost:3000/rspec#/rspec/S2077/
- multiple secondary locations as bullet points under `Secondaries` (free-form) e.g. http://localhost:3000/rspec#/rspec/S1515/python or under "Secondary" (http://localhost:3000/rspec#/rspec/S3519/cfamily )
- multiple secondary locations as `Secondary 1` and `Secondary 2` e.g. http://localhost:3000/rspec#/rspec/S2139/
- language specific message in the generic highlight section (??) e.g. http://localhost:3000/rspec#/rspec/S2755/
- `Primary` w/o bullet point, bullet points for  `Secondary` and `Flow` http://localhost:3000/rspec#/rspec/S2583/
- `Primary` and `Secondary Location` with no bullet points http://localhost:3000/rspec#/rspec/S2786/
- `First` and `Second` e.g http://localhost:3000/rspec#/rspec/S4532/
- `Additional` instead of "secondary" e.g. http://localhost:3000/rspec#/rspec/S107/cfamily .
- `* Additional` with `** Message` e.g. http://localhost:3000/rspec#/rspec/S1526/javascript
- _WARNING_ typos - `secondar` (missing `Y`) e.g. http://localhost:3000/rspec#/rspec/S1534/javascript


Also casing differs "Secondary" vs "secondary" .

**Review by andrei-epure-sonarsource — CHANGES_REQUESTED** [review]
As we've discussed during the standup, this would be a good time to normalize the Parameters (and maybe highlighting as well) to possibly a JSON format which can then be rendered in a uniform fashion in the UI.

Please have a look at the messages I gave regarding the format (which we can use as a test scenario), and also at the bugs I've reported.

**Comment by arseniy-sonar** [comment]
Parsing and unifying of the parameters' representation is left out of scope for this PR in this ticket: [RULEAPI-685](https://jira.sonarsource.com/browse/RULEAPI-685)
I discarded completely the export done until now and took a different approach:
- I used the rule-api to fetch message, parameters, and highlighting fields from Jira and store them in the corresponding individual files: `message.adoc`, `parameters.adoc`, and `highlighting.adoc`.
- Then used [this script](https://github.com/SonarSource/languages-experimental-tooling/blob/master/personal/arseniy-zaostrovnykh/rspec/integrate-impl-spec.py) to include these files in a hidden section of each `rule.adoc`.

**Review by andrei-epure-sonarsource — APPROVED** [review]
LGTM

**Pull request merged**
