### PR TITLE
Modify rule S3743(cfamily): remove a dead link

### PR DESCRIPTION
**Pull request by necto**
## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

### CODE REVIEW

**Comment by necto** [comment]
Why is it a bad practice to link to Internet Archive?
I like the link because it motivates the user to actually make sure no exception is thrown and not simply remove the `noexcept` qualifier.

**Review by kaufco — APPROVED** [review]
LGTM!

**Comment by loic-joly-sonarsource** [comment]
> Why is it a bad practice to link to Internet Archive?
Because it looks like we are an outdated product that references dead resources. Maybe we could ask @John-Clifton-SonarSource (I can't see anything about it in our guidelines about external links)

> I like the link because it motivates the user to actually make sure no exception is thrown and not simply remove the `noexcept` qualifier.
Since we already discuss this specific point in detail in the rule description, I do not feel it is required to have this link.

**Comment by necto** [comment]
Thanks for your input, @John-Clifton-SonarSource 
I removed the link. Feel free to merge, @loic-joly-sonarsource

**Review by loic-joly-sonarsource — APPROVED** [review]

**Pull request merged**
