### PR TITLE
Modify rule S6385: fix section names

### PR DESCRIPTION
**Pull request by pierre-loup-tristant-sonarsource**

### CODE REVIEW

**Comment by hendrik-buchwald-sonarsource** [comment]
This vulnerability still contains the "Recommended Secure Coding Practices" section from hotspots. Do you think it should be removed as well?

**Comment by pierre-loup-tristant-sonarsource** [comment]
Sometime vulnerability rules have the "Recommended Secure Coding Practices" section.
I use it when there is various ways to fix the problem.
On the other hand "Ask Yourself Whether" is to be used exclusively for Security-Hotspot rules.

**Review by hendrik-buchwald-sonarsource — APPROVED** [review]
Okay, LGTM then!

**Comment by hendrik-buchwald-sonarsource** [comment]
@pierre-loup-tristant-sonarsource what about this PR?

**Comment by pierre-loup-tristant-sonarsource** [comment]
It seems like the RSPEC was fixed with another PR 
https://raw.githubusercontent.com/SonarSource/rspec/master/rules/S6385/terraform/rule.adoc

**Pull request closed without merging**
